### PR TITLE
Added icons for pool group file lifetime and quota info pages.

### PR DESCRIPTION
**Pull request by alrossi**

### CODE REVIEW

**Comment by paulmillar** [comment]
The patch seems to have a number of apparently unintended consequences:

A fair bit of icon definitions being moved within the file.  This is undesirable as it makes patch messy.

The patch also appears to ...

REMOVE the icons: `cell-admin`, `pool-queues`, `poolgroups`, `pool-admin`,.

ADD the icon `pool-group-lifetime`

RENAME the icons:
    `pool-usage` --> `pool-info`, 
    `pool-queue-plots` --> `pool-plots`, 
    `pool-selection-setup` --> `pool-selection`

**Comment by alrossi** [comment]
This is a consequence of the fact that the repository was not properly integrated.  I believe it is missing a number of updates from Femi’s private repository.   Those older icons had already been removed.   Note that the tagged version we depend on is 0.0.7.  It is not in the imported repository.   Check out, for instance:   https://github.com/alrossi/admin-page/commit/b254baad3191d374b0e17322a9847f7eab1e476b

**Comment by paulmillar** [comment]
That not withstanding, the patch is still wrong because it is ...
   * moving icons around within the file, needlessly inflating the patch size and making it harder to see what's going on.
  *  doing more than the commit message says: deleting icons and renaming others.

If we have a problem with the current set of icons being somehow "wrong" (unused icons, wrong name) then those problems should be fixed (I think) in a separate patch.

**Comment by alrossi** [comment]
Wouldn't it be better to redo the import so that it pulls in everything from the original?

**Comment by alrossi** [comment]
This is the diff of the original compared to the dCache repo:

```
Alberts-MBP:admin-page-orig arossi$ git log --reverse --no-merges --format='    * [%h] %s'
    * [e403851] add gitignore file
    * [1d4fd32] main commit
    * [ced32c4] update bower.json file
    * [caa944e] adjust the element discription inside readme file
    * [61713d4] add missing icons
    * [d32db18] changed iron-meta creation to imperative declaration and limiting the list to just admins icons
    * [16d35a6] add more style to iron-icon on mouse-over
    * [e66ccaa] change some styling of the in active components
    * [0796744] remove h2 tag
    * [978bf95] redesign demo page
    * [e76ce08] move the logic inside the attached callback into the ready callback.
    * [55f75cf] update to polymer 2.x
    * [e91542e] minor bug fix
    * [75802da] use on-tap instead of href on the anchor tag
    * [b254baa] rearrange the icons to suit Al's needs
    * [8bb12cf] change the active-transfers icon
    * [2f2ca4f]         add icon for pool group file lifetime page
   ```
```
Alberts-MBP:admin-page arossi$ git log --reverse --no-merges --format='    * [%h] %s'
    * [e403851] add gitignore file
    * [1d4fd32] main commit
    * [ced32c4] update bower.json file
    * [caa944e] adjust the element discription inside readme file
    * [61713d4] add missing icons
    * [d32db18] changed iron-meta creation to imperative declaration and limiting the list to just admins icons
    * [16d35a6] add more style to iron-icon on mouse-over
    * [e66ccaa] change some styling of the in active components
    * [0796744] remove h2 tag
    * [978bf95] redesign demo page
    * [e76ce08] move the logic inside the attached callback into the ready callback.
```

There is a lot more missing than just the changes to icons.

**Pull request merged**
